"""Rule-based signal engine.

READ THIS BEFORE QUOTING ANY NUMBER FROM THIS MODULE.

These are *descriptive* rules over synthetic order flow, not predictions.
There is no backtest, no forward return, no profitability measurement, and no
claim that any of it would make money. The data is generated by a random walk
with no learnable structure, so a positive result here would be measuring the
random seed, not a strategy.

What the module genuinely demonstrates is the engineering: a windowed
comparison of two adjacent periods, a documented rule set, a confidence score
that is a stated function of the inputs rather than a black box, and a full
audit string on every output.

The rules
---------
For each symbol, split its most recent `2 * window` trades into an older half
and a newer half, then compare:

  momentum     = (recent VWAP / prior VWAP - 1) * 100
  volume_ratio = recent total quantity / prior total quantity

  BUY   if momentum >  +MOMENTUM_THRESHOLD_PCT and volume_ratio >= 1.0
  SELL  if momentum <  -MOMENTUM_THRESHOLD_PCT and volume_ratio >= 1.0
  HOLD  otherwise

VWAP rather than a simple mean price, because a mean weights a 1-lot the same
as a 10,000-lot. The volume condition exists so a price move on collapsing
volume produces HOLD rather than a signal - thin-tape moves are the least
reliable ones.
"""

from __future__ import annotations

import pandas as pd

from .config import Settings, settings as default_settings
from .models import Signal, SignalAction

MOMENTUM_THRESHOLD_PCT: float = 0.15
# Confidence saturates here: a 1.5% move scores the same 1.0 as a 15% move,
# because beyond a point "more extreme" stops meaning "more trustworthy".
CONFIDENCE_SATURATION_PCT: float = 1.5


def _vwap(frame: pd.DataFrame) -> float:
    """Volume-weighted average price. Returns 0.0 for an empty/zero-volume slice."""
    quantity = float(frame["quantity"].sum())
    if quantity <= 0:
        return 0.0
    return float((frame["quantity"] * frame["price"]).sum() / quantity)


def generate_signals(frame: pd.DataFrame, config: Settings | None = None) -> list[Signal]:
    """Produce one signal per symbol with enough recent history.

    A symbol needs at least `2 * window` trades: one window to establish the
    prior period and one for the recent period. Symbols below that produce no
    signal at all rather than a low-confidence guess.

    Complexity:
        Time  O(n log n) - dominated by the timestamp sort. The per-symbol work
              is O(w) on a fixed-size window, so it does not grow with n.
        Space O(n)
    """
    cfg = config or default_settings
    if frame.empty:
        return []

    window = cfg.signal_window
    ordered = frame.sort_values("timestamp")
    signals: list[Signal] = []

    for symbol, group in ordered.groupby("symbol", sort=False):
        if len(group) < 2 * window:
            continue

        recent = group.iloc[-window:]
        prior = group.iloc[-2 * window : -window]

        prior_vwap = _vwap(prior)
        recent_vwap = _vwap(recent)
        if prior_vwap <= 0:
            continue

        momentum_pct = (recent_vwap / prior_vwap - 1.0) * 100.0
        prior_volume = float(prior["quantity"].sum())
        volume_ratio = float(recent["quantity"].sum()) / prior_volume if prior_volume > 0 else 0.0

        if momentum_pct > MOMENTUM_THRESHOLD_PCT and volume_ratio >= 1.0:
            action = SignalAction.BUY
        elif momentum_pct < -MOMENTUM_THRESHOLD_PCT and volume_ratio >= 1.0:
            action = SignalAction.SELL
        else:
            action = SignalAction.HOLD

        # Confidence is a declared function of the two inputs, capped at 1.0:
        # momentum magnitude carries 70% of the weight, volume support 30%.
        momentum_component = min(abs(momentum_pct) / CONFIDENCE_SATURATION_PCT, 1.0)
        volume_component = min(volume_ratio / 2.0, 1.0)
        confidence = 0.0 if action is SignalAction.HOLD else round(
            0.7 * momentum_component + 0.3 * volume_component, 4
        )

        if action is SignalAction.HOLD:
            reason = (
                f"VWAP moved {momentum_pct:+.2f}% (threshold "
                f"+/-{MOMENTUM_THRESHOLD_PCT}%) on {volume_ratio:.2f}x prior volume - "
                "no rule condition met."
            )
        else:
            reason = (
                f"Recent VWAP {recent_vwap:.2f} vs prior {prior_vwap:.2f} "
                f"({momentum_pct:+.2f}%) on {volume_ratio:.2f}x prior volume over "
                f"{window} trades."
            )

        signals.append(
            Signal(
                symbol=str(symbol),
                action=action,
                confidence=confidence,
                reason=reason,
                momentum_pct=round(momentum_pct, 4),
                volume_ratio=round(volume_ratio, 4),
                sample_size=int(len(group)),
            )
        )

    signals.sort(key=lambda s: s.confidence, reverse=True)
    return signals
